### ISSUE TITLE
Missing `.do` | Unable to deploy to Digital Ocean with the deploy button

### ISSUE THREAD

**Issue by soumendrak** [digitalocean/sample-flask#13]
## App detection failed - Missing app spec file

Unable to deploy this repo to Digital Ocean due to the following error.

<img width="1239" alt="sample-flask-error" src="https://user-images.githubusercontent.com/10120538/133895906-3479dc5b-6c4c-4730-8ded-1becc7ffb507.png">

**Comment by kamaln7** [comment]
Thanks for reporting this, @soumendrak! Sorry we missed it. This is now fixed thanks to @erhan's PR #16.

**Comment by soumendrak** [comment]
Thanks a lot, @kamaln7 and @erhan for the fix. :)
