### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by sebastiandres** [digitalocean/sample-flask#9]
Hi, 
   Great starter repo for flask, thanks! I could deploy to DO with few clicks. 
I wanted to point out that one image is not displaying.
It seems the asset link is not available https://assets.codepen.io/43365/logo.svg

 Everything else seems fine, though!

<img width="940" alt="Screen Shot 2021-05-13 at 16 29 49" src="https://user-images.githubusercontent.com/1276326/118183767-7de79880-b408-11eb-8cf6-927aa275bd3d.png">

**Comment by kamaln7** [comment]
Hi @sebastiandres, thanks for letting us know! We'll sort this out :)
